
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" contenâ¶t="width=device-width, initial-scale=1.0">
    <title>The Great Generation</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #333;
            color: #fff;
            padding: 20px;
            text-align: center;
        }

        nav {
            background-color: #555;
            color: #fff;
            padding: 10px;
            text-align: center;
        }

        nav ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        nav li {
            display: inline-block;
            margin: 0 10px;
        }

        main {
            padding: 20px;
        }

        footer {
            background-color: #666;
            color: #555;
            padding: 10px;
            text-align: center;
        }

        @media screen and (max-width: 768px) {
            nav li {
                display: block;
                margin: 10px 0;
            }
        }
    </style>
</head>
<body>
    <header>
        <h1>Welcome to My first web page</h1>
    </header>

    <nav>
        <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
    </nav>

    <main>
        <h2>About Me</h2>
        <p> A motivational speak and writer we want to see the betterment in the youngergeneration</p>

        <h2>Contact</h2>
        <p> Emaile: davidalmah3@gmail.com!</p>
    </main>

    <footer>
        <p>&copy; 2023. All rights reserved.</p>
    </footer>
</body>
</html>

<html>
